{
 "title": "Prod--DM-worker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "task",
    "query": "label_values(dm_worker_task_state, task)"
   },
   {
    "name": "instance",
    "query": "label_values(dm_worker_task_state{task=\"$task\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "DM子任务状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_worker_task_state{job=\"dm_exporter\"}",
     "legendFormat": "dm子任务状态"
    }
   ]
  },
  {
   "title": "overview (multiple instances)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "task state",
     "type": "graph",
     "description": "The current state of subtasks in instances.\n\n0: Invalid\n\n1: New\n\n2: Running\n\n3: Paused\n\n4: Stopped\n\n5: Finished",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_task_state{task=\"$task\"}"
      }
     ]
    },
    {
     "title": "binlog file index",
     "type": "graph",
     "description": "The largest index number of relay log files. E.g. \"value = 1\" indicates \"mysql-bin.000001\"",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "storage capacity",
     "type": "graph",
     "description": "The storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_relay_space{type=\"capacity\"}"
      }
     ]
    },
    {
     "title": "storage remain",
     "type": "graph",
     "description": "The remaining storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dm_relay_space{type=\"available\"}"
      }
     ]
    },
    {
     "title": "binlog file gap between master and relay",
     "type": "graph",
     "description": "The number of binlog files in the relay log that are behind the upstream master",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{node=\"master\"} - ON(instance, job) dm_relay_binlog_file{node=\"relay\"}"
      }
     ]
    },
    {
     "title": "load progress",
     "type": "graph",
     "description": "The data import process percentage of Loader. The value range is 0% ~ 100%",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "dm_loader_progress{task=\"$task\"}"
      }
     ]
    },
    {
     "title": "binlog file gap between master and syncer",
     "type": "graph",
     "description": "The number of binlog files in Syncer that are behind the master",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_binlog_file{task=\"$task\", node=\"master\"} - ON(instance, task, job) dm_syncer_binlog_file{task=\"$task\", node=\"syncer\"}"
      }
     ]
    },
    {
     "title": "shard lock resolving",
     "type": "graph",
     "description": "Is waiting shard DDL lock to be resolved, >0 means waiting",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_shard_lock_resolving{task=\"$task\"}"
      }
     ]
    }
   ]
  },
  { "title": "task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "task state",
   "type": "singlestat",
   "description": "The current state of the subtask in the instance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dm_worker_task_state{task=\"$task\",instance=\"$instance\"}"
    }
   ]
  },
  { "title": "relay log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "storage capacity",
   "type": "singlestat",
   "description": "The storage capacity of the disk occupied by the relay log",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "dm_relay_space{instance=\"$instance\", type=\"capacity\"}"
    }
   ]
  },
  {
   "title": "storage remain",
   "type": "singlestat",
   "description": "The remaining storage capacity of the disk occupied by the relay log",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "dm_relay_space{instance=\"$instance\", type=\"available\"}"
    }
   ]
  },
  {
   "title": "process exits with error",
   "type": "singlestat",
   "description": "The relay log encounters an error within the DM-worker and exits",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(dm_relay_exit_with_error_count{instance=\"$instance\"}[30m])"
    }
   ]
  },
  {
   "title": "relay log data corruption",
   "type": "singlestat",
   "description": "The number of corrupted relay log files",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(dm_relay_data_corruption{instance=\"$instance\"}[30m])"
    }
   ]
  },
  {
   "title": "fail to read binlog from master",
   "type": "singlestat",
   "description": "The number of errors encountered when the relay log reads the binlog from the upstream MySQL",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(dm_relay_read_error_count{instance=\"$instance\"}[30m])"
    }
   ]
  },
  {
   "title": "fail to write relay log",
   "type": "singlestat",
   "description": "The number of errors encountered when the relay log writes the binlog to disks",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(dm_relay_write_error_count{instance=\"$instance\"}[30m])"
    }
   ]
  },
  {
   "title": "write relay log duration",
   "type": "graph",
   "description": "The duration that the relay log writes binlog into the disks each time (in seconds)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_duration_bucket{instance=\"$instance\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "binlog file gap between master and relay",
   "type": "graph",
   "description": "The number of binlog files in the relay log that are behind the upstream master",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_relay_binlog_file{instance=\"$instance\", node=\"master\"} - ON(instance, job) dm_relay_binlog_file{instance=\"$instance\", node=\"relay\"}"
    }
   ]
  },
  {
   "title": "binlog pos",
   "type": "graph",
   "description": "The write offset of the latest relay log file",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_relay_binlog_pos{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "read binlog duration",
   "type": "graph",
   "description": "The duration that the relay log reads binlog from the upstream MySQL (in seconds)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(dm_relay_read_binlog_duration_bucket{instance=\"$instance\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "binlog size",
   "type": "graph",
   "description": "The size of a single binlog event that the relay log writes into the disks",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_size_bucket{instance=\"$instance\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "load dump files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "load progress",
     "type": "singlestat",
     "description": "The data import process percentage of Loader. The value range is 0% ~ 100%",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_progress{task=\"$task\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "data file size",
     "type": "singlestat",
     "description": "The total size of the data files in the full data imported by Loader (including the `INSERT INTO` statement)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_data_size_count{task=\"$task\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "dump process exits with error",
     "type": "singlestat",
     "description": "Dumper encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_mydumper_exit_with_error_count{task=\"$task\",instance=\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "load process exits with error",
     "type": "singlestat",
     "description": "Loader encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_loader_exit_with_error_count{task=\"$task\",instance=\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "table count",
     "type": "singlestat",
     "description": "The total number of tables in the full data imported by Loader",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_table_count{task=\"$task\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "data file count",
     "type": "singlestat",
     "description": "The total number of data files in the full data imported by Loader (including the `INSERT INTO` statement)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_data_file_count{task=\"$task\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "latency of execute transaction",
     "type": "graph",
     "description": "The duration that Loader executes a transaction (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_txn_duration_time_bucket{task=\"$task\", instance=\"$instance\"}[1m])) by (le))"
      }
     ]
    },
    {
     "title": "latency of query",
     "type": "graph",
     "description": "The duration that Loader executes a query (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_query_duration_time_bucket{task=\"$task\", instance=\"$instance\"}[1m])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "binlog  replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "remaining time to sync",
     "type": "singlestat",
     "description": "The predicted remaining time it takes Syncer to be completely synchronized with the master (in minutes)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "format": "m",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_syncer_remaining_time{task=\"$task\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "replicate lag",
     "type": "singlestat",
     "description": "The latency time it takes to replicate the binlog from master to Syncer (in seconds)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_syncer_replication_lag{task=\"$task\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "singlestat",
     "description": "The binlog replication process encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_syncer_exit_with_error_count{task=\"$task\", instance=\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "binlog file gap between master and syncer",
     "type": "graph",
     "description": "The number of binlog files in Syncer that are behind the master",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_binlog_file{instance=\"$instance\", task=\"$task\", node=\"master\"} - ON(instance, task, job) dm_syncer_binlog_file{instance=\"$instance\", task=\"$task\", node=\"syncer\"}"
      }
     ]
    },
    {
     "title": "binlog file gap between relay and syncer",
     "type": "graph",
     "description": "The number of binlog files in Syncer that are behind relay",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=\"$instance\", node=\"relay\"} - ON(instance, job) dm_syncer_binlog_file{instance=\"$instance\", task=\"$task\", node=\"syncer\"}"
      }
     ]
    },
    {
     "title": "binlog event qps",
     "type": "graph",
     "description": "The number of binlog events received per unit of time (this number does not include the events that need to be skipped)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_binlog_transform_cost_count{task=\"$task\", instance=\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "skipped binlog event qps",
     "type": "graph",
     "description": "The number of binlog events received per unit of time that need to be skipped",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_binlog_skipped_events_total{task=\"$task\", instance=\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "cost of binlog event  transform",
     "type": "graph",
     "description": "The time it takes Syncer to parse and transform the binlog into SQL statements (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_transform_cost_bucket{task=\"$task\", instance=\"$instance\"}[1m])) by (le))"
      }
     ]
    },
    {
     "title": "total  sql jobs",
     "type": "graph",
     "description": "The number of newly added jobs per unit of time",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_added_jobs_total{task=\"$task\", instance=\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "finished  sql jobs",
     "type": "graph",
     "description": "The number of finished jobs per unit of time",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_finished_jobs_total{task=\"$task\", instance=\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "execution latency",
     "type": "graph",
     "description": "The time it takes Syncer to execute the transaction to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_txn_duration_time_bucket{task=\"$task\", instance=\"$instance\"}[1m])) by (le))"
      }
     ]
    },
    {
     "title": "unsynced tables",
     "type": "graph",
     "description": "The number of unsynced tables in the subtask",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_unsynced_table_number{instance=\"$instance\", task=\"$task\"}"
      }
     ]
    },
    {
     "title": "shard lock resolving",
     "type": "graph",
     "description": "Is waiting shard DDL lock to be resolved, >0 means waiting",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_shard_lock_resolving{instance=\"$instance\", task=\"$task\"}"
      }
     ]
    }
   ]
  }
 ]
}